name: social_share_example
description: Demonstrates how to use the social_share plugin.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  screenshot: ^3.0.0
  path_provider: ^2.1.5
  http: ^1.5.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  social_share:
    path: ../

flutter:
  uses-material-design: true
  assets:
   - assets/
  
  
  
  
  
  
  
  
  
  
  
  
  
